version: '3'

services:
  studio-db:
    image: postgres
    environment:
      - GET_HOSTS_FROM=dns
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    networks:
      - internal_network

  studio:
    build: .
    image: registry.demo.scaleout.se/studio:latest #docker.pkg.github.com/scaleoutsystems/registry/studio:latest
    command: sh scripts/run_web.sh
    environment:
      - GET_HOSTS_FROM=dns
    volumes:
      - .:/app:cached
    #ports:
    #  - 8080:8080
    depends_on:
      - studio-db
    links:
      - "studio-db:studio-db.default.svc.cluster.local"
    networks:
      - internal_network

  chart-controller:
    image: registry.demo.scaleout.se/chart-controller:latest
    ports:
      - 80:80
    networks:
      - internal_network

  ingress:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    image: registry.demo.scaleout.se/ingress:latest
    environment:
      - GET_HOSTS_FROM=dns
    container_name: ingress
    volumes:
      - ./scripts/nginx.conf:/etc/nginx/nginx.conf
      - ./repos:/var/www/html/git/repos
    ports:
      - 8080:80
    #  - 443:4430
    depends_on:
      - studio
    networks:
      - internal_network

  redis:
    image: redis
    hostname: redis
    ports:
      - "6379:6379"
    networks:
      - internal_network
  
  rabbit:
    image: rabbitmq
    hostname: rabbit
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=LJqEG9RE4FdZbVWoJzZIOQEI
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - internal_network

  celery-worker:
    build: .
    image: registry.demo.scaleout.se/studio:latest
    command: sh ./scripts/run_worker.sh
    volumes:
      - .:/app:cached
    links:
      - studio-db
      - studio
      - rabbit
      - redis
    depends_on:
      - studio-db
      - studio
      - rabbit
      - redis
    networks:
      - internal_network

networks:
  internal_network:
    driver: bridge
